sudo: false

language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

cache: pip

install:
  - pip install tox-travis

script:
  - travis_wait 30 tox

jobs:
  include:
    - stage: codecov
      python: 3.6
      script:
        - travis_wait 30 tox
        - pip install codecov && codecov

notifications:
  email: false
