sudo: false

language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy3"
  - "nightly"

install:
  - pip install -r requirements-dev.txt

cache: pip

install:
  - pip install tox-travis
  - pip install pysmt
  - (echo y | pysmt-install --z3) && eval $(pysmt-install --env) && pysmt-install --check

script:
  - tox

jobs:
  include:
    - stage: codecov
      python: nightly
      script:
        - tox
        - pip install codecov && codecov --token=$CODECOV_TOKEN

notifications:
  email: false

branches:
 only:
  - master